name: Build 'Entry Envoy' Docker image
on:
    workflow_dispatch:
jobs:
    docker:
        runs-on: ubuntu-24.04
        permissions:
            contents: read      # To checkout the repository code
            packages: write     # To push Docker images to GHCR
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Get git hash
              run: echo "GIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

            - name: Get repository owner in lowercase
              id: lowercase
              run: echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                context: apps/entry-envoy
                push: true
                tags: ghcr.io/${{ env.REPO_OWNER }}/gitops-demo-entry-envoy:sha-${{ env.GIT_HASH }}
                labels: |
                    org.opencontainers.image.source=${{ github.repository }}
