name: Init new environment branch
on:
    workflow_dispatch:
        inputs:
            env_name:
                description: "Environment name (e.g., qa1)"
                required: true
                type: string
            cluster_name:
                description: "Cluster name (e.g., gitops-demo-shared)"
                required: true
                type: string

jobs:
    init-branch:
        name: Create new environment branch ${{ inputs.cluster_name }}/${{ inputs.env_name }}
        uses: ./.github/workflows/reusable-run-devops-cli.yaml
        with:
            args: "init-env-branch"
            env_name: ${{ inputs.env_name }}
            cluster_name: ${{ inputs.cluster_name }}
            aws_region: ${{ vars.AWS_REGION }}
            aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
            manifest_repo: ${{ vars.MANIFEST_REPO }}
        secrets:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            manifest_repo_access_token: ${{ secrets.MANIFEST_REPO_ACCESS_TOKEN }}
